# Generated by Django 4.1 on 2022-08-26 09:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('first_name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Enter a valid name', regex='^[A-Za-z][A-Za-z ]*$'), django.core.validators.MinLengthValidator(3, 'Min 3 char required')])),
                ('last_name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Enter a valid name', regex='^[A-Za-z][A-Za-z ]*$'), django.core.validators.MinLengthValidator(3, 'Min 3 char required')])),
                ('user_name', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('phone_number', models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999999'. Up to 13 digits allowed.", regex='^\\+?1?\\d{9,13}$')])),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now_add=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superadmin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
